apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
  labels:
    app: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        #ports:
        #- containerPort: 5432
        #  protocol: TCP
        env:
          - name: POSTGRES_USER
            value: "movie_db_username"
          - name: POSTGRES_PASSWORD
            value: "movie_db_password"
          - name: POSTGRES_DB
            value: "movie_db_dev"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: movie-db
  name: movie-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: movie-db